language: 'node_js'
node_js: '8'

before_script:
  - npm install
  - npm run build
  - cp ./build/index.html ./build/404.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: ./build
  repo: christopherkade/lockdown.center
  fqdn: lockdown.center
  target_branch: gh-pages
  on:
    branch: master